"use client";
import Header from "@/Components/Header/Header";
import "./globals.css";
import { Saira } from "next/font/google";
import { FilterContextProvider } from "@/Context/FilterContext/FilterContext";

const saira = Saira({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata = {
  title: "Capputeeno",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <FilterContextProvider>
          <Header />
          {children}
        </FilterContextProvider>
      </body>
    </html>
  );
}
