import Header from '@/components/header'
import './globals.css'
import type { Metadata } from 'next'
import { Saira } from 'next/font/google'
import DefaultProvider from '@/components/default-provider'
import StyledComponentsRegistry from '@/lib/registry'



const saira = Saira({ 
  weight:['300','400','500','600'],
  subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: 'Capputeeno',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <DefaultProvider>
        <StyledComponentsRegistry>
          <Header/>
          {children}
        </StyledComponentsRegistry>
        </DefaultProvider>
      </body>
    </html>
  )
}
