import Header from '@/components/header'
import StyledComponentsRegistry from '@/lib/registry'
import { DefaultProvider } from '@/components/default-provider'
import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Saira_Stencil_One } from 'next/font/google'

const saira = Saira_Stencil_One({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'capputeeno',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <DefaultProvider>
        <body className={saira.className}>
          <Header />
          {children}
        </body>
      </DefaultProvider>
    </html>
  )
}
